### PR TITLE
Fix gpg-agent run and provide automated login process

### PR DESCRIPTION
**Pull request by jeffreystoke**
The main purpose of this pull request is to fix gpg key generation when initializing as mentioned in #34 

Another purpose is to provide a way to login automatically when initializing, however my eventual goal is to have a automated login/serving process with consistent smtp username/password without storing generated data locally.

__NOTE:__ Only updated the `build` directory and `README.md`

### CODE REVIEW

**Comment by shenxn** [comment]
Thanks! Can you split this PR? One for gpg and one for automatic login?

**Comment by jeffreystoke** [comment]
@shenxn sure, and what I believe even better is to have a clear agreement on following questions:

1. Do we really want to maintain two different login flows even when we can make them one? (https://github.com/shenxn/protonmail-bridge-docker/issues/36#issuecomment-864370762)
2. Do we really want to keep the official deb installation when we can compile it without cgo support in alpine? (we can change two lines in the source code to get rid of gnome-keyring)

If both answers are `NO`, what if I just start a new pull request with all these features packed and drop backwards compatibility?

**Comment by jeffreystoke** [comment]
FYI: To compile in alpine container without cgo:

```bash
sed -i 's/github.com\/docker\/docker-credential-helpers\/secretservice/fmt/g' proton-bridge/pkg/keychain/helper_linux.go
sed -i 's/return \&secretservice\.Secretservice.*, nil/return nil, fmt\.Errorf\("not supported"\)/g' proton-bridge/pkg/keychain/helper_linux.go
```

**Comment by jeffreystoke** [comment]
Related work has been done in my dockerfile repo since I could not build image in a forked repo

the dockerfile: https://github.com/arhat-dev/dockerfile/blob/master/app/proton-bridge.dockerfile
and related build scripts: https://github.com/arhat-dev/dockerfile/blob/master/scripts/app/app.mk#L40
usage instruction: https://github.com/arhat-dev/helm-charts/tree/master/charts/proton-bridge

**Comment by shenxn** [comment]
I do think it is time to drop deb version. To avoid breaking changes, maybe it is better to give the new image a new name. I don't want to make any changes to the source code though because currently I rely on cron job to check update and bump versions automatically. Those kind of changes can break at any time. I think it is fine to keep using ubuntu as base image.

**Comment by shenxn** [comment]
I'll actually create a new repo for this to make sure the current version is working without problem for a while.

**Comment by jeffreystoke** [comment]
So I guess it's better to keep the fix part only in this pull request, right?

**Comment by jeffreystoke** [comment]
And the automated login flow should be implemented in your new repo, correct?

**Comment by shenxn** [comment]
Yeah. I'll ping you when the new repo is ready.

**Comment by jeffreystoke** [comment]
@shenxn any progress?

I was busy doing other things recently, please let me know if I missed anything.

**Pull request merged**
